# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 23:36
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models
import functools
import thorn.utils.compat


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='hmac_digest',
            field=models.CharField(
                choices=[
                    ('SHA512', 'sha512'),
                    ('SHA256', 'sha256'),
                    ('SHA1', 'sha1')],
                default='sha256',
                help_text='Specify HMAC digest type (use sha256 if uncertain)',
                max_length=64, verbose_name='HMAC Digest Type'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hmac_secret',
            field=models.TextField(
                default=functools.partial(
                    thorn.utils.compat.random_secret, *(64,), **{}),
                help_text='Specify HMAC secret for endpoints to verify',
                verbose_name='HMAC Secret'),
        ),
    ]
