# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_auto_20160523_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set([]),
        ),
    ]
