# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 18:54
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberlog',
            name='subscription',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
